language: python
python:
#  - "2.6"
#  - "2.7"
#  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - pip install simplejson
# command to run tests
script: 
  - python -m doctest -v DocTestExample.py
  - python -m unittest unittestExample -v
